### ISSUE TITLE
Deprecated NumPy 1.25.

### ISSUE THREAD

**Issue by JooHyoSeok** [rsasaki0109/particle_filtering_model_predictive_control#1]
If you modify the code at line 225~228, you can run the simulator.

before : 
        x.append(state.x)
        y.append(state.y)
        yaw.append(state.yaw)
        v.append(state.v)
after : 
        x.append(*state.x)
        y.append(*state.y)
        yaw.append(*state.yaw)
        v.append(*state.v)

**Comment by rsasaki0109** [comment]
Sorry, I just noticed your comment now. Thank you for pointing it out. I will make the correction.

**Comment by rsasaki0109** [comment]
Fixed! Thanks for pointing it out!
The issue has been resolved, so I'm closing this now.
